const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={events:[],source:null,running:false,autoScroll:true,complete:null};
const els={run:$('#runBtn'),reset:$('#resetBtn'),timeline:$('#timeline'),runId:$('#runId'),core:$('#securityCore'),coreState:$('#coreState'),score:$('#scoreValue'),scoreProgress:$('#scoreProgress'),controls:$('#controlsMetric'),chain:$('#chainMetric'),provenance:$('#provenanceMetric'),verdict:$('#verdictMetric'),eventCount:$('#eventCount'),passport:$('#passportWrap'),terminalHash:$('#terminalHash'),uiLed:$('#uiChainLed'),uiText:$('#uiChainText'),backendLed:$('#backendChainLed'),backendText:$('#backendChainText'),pause:$('#pauseBtn'),intelPhase:$('#intelPhase'),intelTitle:$('#intelTitle'),intelText:$('#intelText'),intelHash:$('#intelHash')};
const edgeMap={sentinel_agent:'edge-sentinel',red_agent:'edge-red',forensic_agent:'edge-forensic',defense_agent:'edge-defense',provenance_agent:'edge-provenance',judge_agent:'edge-judge'};
const titles={CERTIFICATION_STARTED:'Mission initialized',TRUST_BOUNDARY_MAPPED:'Trust boundary mapped',ATTACK_OBSERVED:'Adversarial pressure detected',ROOT_CAUSE_FOUND:'Causal fault isolated',PATCH_APPLIED:'Policy mutation deployed',ATTACK_REPLAYED:'Attack replay in progress',PROVENANCE_ATTESTED:'Evidence lineage attested',JUDGE_VERDICT:'Independent verdict reached',TRUST_PASSPORT_ISSUED:'Trust Passport issued',CERTIFICATION_BLOCKED:'Certification denied'};
function setCore(label,kind=''){els.coreState.textContent=label;els.core.className='core '+kind}
function activate(actor,phase){$$('[data-agent]').forEach(n=>n.classList.remove('active'));$$('.links path').forEach(p=>p.classList.remove('active'));const n=$(`[data-agent="${actor}"]`);if(n)n.classList.add('active');if(edgeMap[actor])$('#'+edgeMap[actor])?.classList.add('active');$$('.phase-rail div').forEach(x=>{x.classList.remove('active');if(x.dataset.phase===phase)x.classList.add('active')})}
function statusClass(s){if(['COMPROMISED','CRITICAL','CONTROL_FAILED','BLOCKED','INVALID'].includes(s))return'bad';if(['CERTIFIED','CONTROL_HELD','HARDENED','VERIFIED','BASELINED'].includes(s))return'good';if(s==='HUMAN_APPROVAL_REQUIRED')return'warn';return''}
function shortHash(v){return v?`${v.slice(0,10)}…${v.slice(-8)}`:'—'}
function addEvent(e){state.events.push(e);if($('.empty'))els.timeline.innerHTML='';const c=document.createElement('div');c.className=`ecard ${statusClass(e.status)}`;c.innerHTML=`<div class="eseq">#${String(e.seq).padStart(2,'0')}</div><div class="etype">${e.event_type}</div><div class="esummary">${e.summary}</div><div class="emeta"><b>${e.status}</b><code>${shortHash(e.event_hash)}</code></div>`;els.timeline.appendChild(c);els.eventCount.textContent=`${state.events.length} EVENTS`;if(state.autoScroll)els.timeline.scrollTop=els.timeline.scrollHeight;els.intelPhase.textContent=(e.phase||'LIVE').toUpperCase();els.intelTitle.textContent=titles[e.event_type]||e.event_type;els.intelText.textContent=e.summary;els.intelHash.textContent=shortHash(e.event_hash);handleEvent(e);verifyUiChain()}
function matrixUpdate(e,which){const t=e.payload?.test,r=t&&$(`[data-test="${t}"]`);if(!r)return;const d=e.payload?.result?.decision||e.status,cell=r.querySelector('.'+which);cell.textContent=d;cell.className=which+' '+(d==='ALLOWED'?'status-bad':d==='BLOCKED'?'status-good':'status-warn');if(which==='hardened'){const ok=['BLOCKED','HUMAN_APPROVAL_REQUIRED'].includes(d),c=r.querySelector('.control');c.textContent=ok?'PROVEN':'FAILED';c.className='control '+(ok?'status-good':'status-bad')}}
function handleEvent(e){activate(e.actor,e.phase);switch(e.event_type){case'CERTIFICATION_STARTED':setCore('SCANNING');break;case'TRUST_BOUNDARY_MAPPED':setCore('BASELINED');break;case'ATTACK_OBSERVED':if(e.status==='COMPROMISED')setCore('BREACHED','compromised');matrixUpdate(e,'baseline');break;case'ROOT_CAUSE_FOUND':setCore('DIAGNOSING','compromised');break;case'PATCH_APPLIED':setCore('MUTATING','hardened');showPatch();break;case'ATTACK_REPLAYED':setCore('RE-ATTACK','hardened');matrixUpdate(e,'hardened');break;case'PROVENANCE_ATTESTED':els.provenance.textContent=e.status;break;case'JUDGE_VERDICT':els.controls.textContent=`${e.payload?.tests_passed??0}/${e.payload?.tests_total??4}`;els.verdict.textContent=e.status;break;case'TRUST_PASSPORT_ISSUED':setCore('ATTESTING','hardened');break;case'CERTIFICATION_BLOCKED':setCore('DENIED','compromised');break}}
function showPatch(){const p=$('#diffPanel');p.classList.add('repaired');$('.patch-state').textContent='MUTATED';const vals=[['#diffDoc','trusted','untrusted'],['#diffRecipient','allowed','denied'],['#diffGrounding','false','true'],['#diffLoop','8','3']];vals.forEach(([id,a,b])=>{const row=$(id).parentElement;$(id).textContent=a;row.querySelector('.after').textContent=b})}
function verifyUiChain(){let ok=true;state.events.forEach((e,i)=>{if(i===0?e.previous_hash!=='GENESIS':e.previous_hash!==state.events[i-1].event_hash)ok=false});els.uiLed.className=ok?'good':'bad';els.uiText.textContent=ok?'VERIFIED':'BROKEN';return ok}
function finish(d){state.complete=d;state.running=false;els.run.disabled=false;els.run.innerHTML='<span class="launch-orb"></span><span>INITIATE GAUNTLET</span><small>LIVE EVIDENCE RUN</small>';els.runId.textContent=d.run_id;els.terminalHash.textContent=d.terminal_event_hash||'—';const ui=verifyUiChain();els.backendLed.className=d.audit_chain_valid?'good':'bad';els.backendText.textContent=d.audit_chain_valid?'VERIFIED':'INVALID';els.chain.textContent=d.audit_chain_valid?'VERIFIED':'INVALID';els.provenance.textContent=d.provenance_attested?'ATTESTED':'FAILED';els.verdict.textContent=d.certificate;const valid=d.certificate==='CERTIFIED'&&d.audit_chain_valid&&d.provenance_attested&&ui;if(valid){setCore('CERTIFIED','certified');unlockScore(d.trust_score);showPassport(d,ui)}else{setCore('DENIED','compromised');els.score.textContent='0'}if(state.source){state.source.close();state.source=null}}
function unlockScore(score){els.score.textContent=score;const c=2*Math.PI*94;els.scoreProgress.style.strokeDasharray=c;els.scoreProgress.style.strokeDashoffset=c*(1-score/100)}
function showPassport(d,ui){els.passport.hidden=false;$('#passportStatus').textContent=d.certificate;$('#passportScore').textContent=d.trust_score;$('#passportControls').textContent=els.controls.textContent+' VERIFIED';$('#passportBackendChain').textContent=d.audit_chain_valid?'VERIFIED':'INVALID';$('#passportProvenance').textContent=d.provenance_attested?'ATTESTED':'FAILED';$('#passportUiChain').textContent=ui?'VERIFIED':'INVALID';$('#passportRun').textContent=d.run_id;$('#passportHash').textContent=d.terminal_event_hash;setTimeout(()=>els.passport.scrollIntoView({behavior:'smooth',block:'center'}),450)}
function reset(){if(state.source)state.source.close();state.events=[];state.complete=null;state.running=false;els.timeline.innerHTML='<div class="empty"><span>◌</span>NO EVIDENCE CAPTURED</div>';els.runId.textContent='STANDBY';els.eventCount.textContent='0 EVENTS';els.controls.textContent='0/4';els.chain.textContent='WAIT';els.provenance.textContent='WAIT';els.verdict.textContent='PENDING';els.score.textContent='--';els.scoreProgress.style.strokeDashoffset=591;els.passport.hidden=true;els.terminalHash.textContent='—';els.uiLed.className=els.backendLed.className='';els.uiText.textContent=els.backendText.textContent='WAITING';els.intelPhase.textContent='STANDBY';els.intelTitle.textContent='Awaiting mission';els.intelText.textContent='Initiate the gauntlet to watch the agent mesh attack, diagnose, repair and certify in real time.';els.intelHash.textContent='—';setCore('DORMANT');$$('[data-agent],.links path,.phase-rail div').forEach(x=>x.classList.remove('active','done'));$$('.mrow').forEach(r=>{r.querySelector('.baseline').textContent='—';r.querySelector('.hardened').textContent='—';r.querySelector('.control').textContent='WAIT';r.querySelectorAll('b,em').forEach(x=>x.classList.remove('status-bad','status-good','status-warn'))});$('#diffPanel').classList.remove('repaired');$('.patch-state').textContent='ARMED';[['#diffDoc','trusted'],['#diffRecipient','allowed'],['#diffGrounding','false'],['#diffLoop','8']].forEach(([id,v])=>{$(id).textContent=v;$(id).parentElement.querySelector('.after').textContent='?'});els.run.disabled=false;els.run.innerHTML='<span class="launch-orb"></span><span>INITIATE GAUNTLET</span><small>LIVE EVIDENCE RUN</small>'}
function run(){reset();state.running=true;els.run.disabled=true;els.run.innerHTML='<span class="launch-orb"></span><span>GAUNTLET ACTIVE</span><small>STREAMING LIVE EVIDENCE</small>';const src=new EventSource('/api/v1/gauntlet/stream?target=synthetic_procurement_agent&pace_ms=430');state.source=src;src.addEventListener('trustforge_event',ev=>{const e=JSON.parse(ev.data);els.runId.textContent=e.run_id;addEvent(e)});src.addEventListener('trustforge_complete',ev=>finish(JSON.parse(ev.data)));src.onerror=()=>{if(state.running){els.run.disabled=false;els.run.innerHTML='<span class="launch-orb"></span><span>RETRY GAUNTLET</span><small>STREAM INTERRUPTED</small>';$('#healthText').textContent='STREAM LOST'}src.close()}}
async function health(){try{const r=await fetch('/healthz');if(!r.ok)throw 0;const d=await r.json();$('#healthText').textContent=d.status==='ok'?'BACKEND ONLINE':'DEGRADED';const a=await fetch('/api/v1/agents');if(a.ok){const j=await a.json();$('#fleetCount').textContent=(j.specialists?.length||6)+1;if(j.certification_invariant)$('#invariant').textContent=j.certification_invariant}}catch{$('#healthText').textContent='BACKEND OFFLINE';$('#healthDot').style.background='var(--red)'}}
els.run.addEventListener('click',run);els.reset.addEventListener('click',reset);els.pause.addEventListener('click',()=>{state.autoScroll=!state.autoScroll;els.pause.textContent=state.autoScroll?'PAUSE':'RESUME'});$('#copyHashBtn').addEventListener('click',async()=>{if(state.complete?.terminal_event_hash){await navigator.clipboard.writeText(state.complete.terminal_event_hash);$('#copyHashBtn').textContent='COPIED';setTimeout(()=>$('#copyHashBtn').textContent='COPY PROOF',1200)}});health();